/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/basket`; params?: Router.UnknownInputParams; } | { pathname: `/details`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modal)'}/dish` | `/dish`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modal)'}/filter` | `/filter`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modal)'}/location-search` | `/location-search`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/basket`; params?: Router.UnknownOutputParams; } | { pathname: `/details`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(modal)'}/dish` | `/dish`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(modal)'}/filter` | `/filter`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(modal)'}/location-search` | `/location-search`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/basket${`?${string}` | `#${string}` | ''}` | `/details${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(modal)'}/dish${`?${string}` | `#${string}` | ''}` | `/dish${`?${string}` | `#${string}` | ''}` | `${'/(modal)'}/filter${`?${string}` | `#${string}` | ''}` | `/filter${`?${string}` | `#${string}` | ''}` | `${'/(modal)'}/location-search${`?${string}` | `#${string}` | ''}` | `/location-search${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/basket`; params?: Router.UnknownInputParams; } | { pathname: `/details`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modal)'}/dish` | `/dish`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modal)'}/filter` | `/filter`; params?: Router.UnknownInputParams; } | { pathname: `${'/(modal)'}/location-search` | `/location-search`; params?: Router.UnknownInputParams; };
    }
  }
}
